app:
  port: 3000
  global_request_timeout: 5000


log:
  ERROR: 1
  INFO: 1
  LOG: 1
  WARN: 1
  DEBUG: 1


dbs:
  -
    type: mongodb
    name: cmd-server
    port: 27017
    server: '127.0.0.1'


paths:
  cmds: '/test/app/cmds'
  schemas: '/test/app/schemas'
  interceptors: '/test/app/lib/interceptors'
  transformers: '/test/app/lib/transformers'


apis:
  # can be overidden on per api basis below
  type: 'application/json'
  paths:

    - path: '/auth/register'
      methods:
        POST:
          cmd: 'users/create'
          transformer: 'user.api'


    - path: '/auth/login'
      methods:
        POST:
          cmd: 'auth/login'
          transformer: 'login.api'


errors:
  # external codes
  BadRequestError:
    status: 400
    message: 'Bad Request.'
  UnauthorizedError:
    status: 401
    message: 'Invalid Session.'
  ForbiddenError:
    status: 403
    message: 'You cannot access the requested service.'
  NotFoundError:
    status: 404
    message: 'Resource not found.'
  AuthenticationTimeOutError:
    status: 419
    message: 'Your session has expired.'
  RequestTimeoutError:
    status: 408
    message: 'Request Timeout.'
  InternalServerError:
    status: 500
    message: 'Internal Server Error.'
  NotImplementedError:
    status: 501
    message: 'This service has not yet been implemented.'
  ServiceUnavailableError:
    status: 503
    message: 'This service is currently not available.'
  # internal codes
  InvalidInputError:
    status: 1000
    message: 'Invalid Input.'
  InvalidOutputError:
    status: 1001
    message: 'Invalid Output.'
